version: '3'

services:
  app:
    image: egoexpress/bind
    restart: always

    # use network stack of OpenVPN container on the same host
    network_mode: container:openvpn_app_1
    volumes:
      - config:/bind

volumes:
  config:
